name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  SERVICE_NAME: 'my-us-stock'
  SERVICE_REGION: ${{ secrets.SERVICE_REGION }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: yarn install
        run: yarn install

      - name: generate prisma client to use prisma
        run: npx prisma generate

      - name: setup test db
        run: docker compose up -d

      - name: execute unit test
        env:
          DATABASE_URL: postgresql://root:admin@localhost:5434/stock?schema=public
        run: npm run test

      - name: Create version file
        run: |
          echo "{\"commit\": \"${{ github.sha }}\"}" > version.json

      - name: Print working directory
        run: pwd

      - name: List files in the directory
        run: ls -l

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} \
            --platform managed \
            --region ${{ env.SERVICE_REGION }} \
            --allow-unauthenticated
